configs:
  - model: "100_100_0.6_450_lstm"
    lstm_layers: [100,100]
    epochs: 50
    batch_size: 450
    label_max: 15
    buy_thresh: 0.6
    label_gt: 3
    strategy:
        pct_gain: 0.15
        pct_loss: 100
        days_to_hold: 4
  - model: "100_100_0.6_900_lstm"
    lstm_layers: [100,100]
    epochs: 50
    batch_size: 900
    label_max: 15
    buy_thresh: 0.6
    label_gt: 3
    strategy:
        pct_gain: 0.15
        pct_loss: 100
        days_to_hold: 4
